import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Dental Health",
  description: "Generated by create next app",
  icons: ["/images/Iconlogo.svg"],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container mx-auto  max-w-screen-2xl">{children}</div>
      </body>
    </html>
  );
}
